### ISSUE TITLE
egg-hashids包名称错误

### ISSUE THREAD

**Issue by jpgaus** [weihongyu12/egg-hashids#1]
安装是eggjs-hashids
配置是package: 'egg-hashids',
启动时，提示包不存在，将配置改为eggjs-hashids正常。

参照其他样例，配置那还是写egg-hashids统一。

**Comment by weihongyu12** [comment]
谢谢您的反馈！

文档已经更新，配置`package: 'eggjs-hashids'`即可使用

egg-hashids的包名已经被占用了无法使用

**Comment by jpgaus** [comment]
很好用，谢谢回复!
